server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: productRoute
          uri: lb://ms-product
          predicates:
            - Path=/products/**
          filters:
            - AddRequestHeader=custom-header, RequestTestHeader
            - AddResponseHeader=custom-header, ResponseTestHeader
        - id: catalogRoute
          uri: lb://ms-catalog
          predicates:
            - Path=/catalog/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    urlService:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

management:
  endpoints:
    exposure:
      include: info, health, refresh, gateway
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    refresh:
      enabled: true
    gateway:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Api Gateway
    version: 1.0.0
