server:
  port: 8888

spring:
  application:
    name: ms-config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/erickvaernet/ms-configuration-files